# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cipto Hartanto
email: hi@ciptohartanto.com
description: Cipto Hartanto is a visual designer with interests in front-end architecture, UI/UX research and development, and photography. He now lives in Taipei.

# baseurl: "" # the subpath of your site, e.g. /blog
# keywords: Cipto Hartanto UI/UX designer Indonesia Taiwan 陳積多 sharing music photography
# url: "http://localhost:3000/" # the base hostname & protocol for your site
baseurl: "cipto-portfolio/"

collections:
    portfolio:
        output: true
        permalink: /portfolio/:path/


# Build settings
markdown: kramdown


exclude: ["node_modules",
"gulpfile.js",
"package.json",
"about.md",
"jade"]
